server:
  port: 1111
spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/chad_used/spring_cloud_config.git
          search-paths: hklk-spring-cloud-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/